In [1]:
import numpy as np

print("NumPy Version:", np.__version__)

arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_0d = np.array(42)
arr_ones = np.ones((3, 3))

print(arr_1d)
print(arr_2d)
print(arr_0d)
print(arr_ones)

print(arr_1d[2])
print(arr_2d[1, 2])
print(arr_1d[1:4])
print(arr_2d[1, :])

arr_a = np.array([10, 20, 30])
arr_b = np.array([1, 2, 3])

print(arr_a + arr_b)
print(arr_a - arr_b)
print(arr_a * arr_b)
print(arr_a / arr_b)
print(arr_a * 2)

print(np.sum(arr_a))
print(np.mean(arr_a))
print(np.std(arr_a))

print(arr_a > arr_b)

print(arr_a[arr_a > 15])

indices = [0, 2]
print(arr_a[indices])

reshaped_arr = arr_1d.reshape(5, 1)
print(reshaped_arr)

structured_arr = np.array(
    [(25, 90.5), (30, 85.2)],
    dtype=[('age', 'i4'), ('score', 'f4')]
)

print(structured_arr)

NumPy Version: 2.3.5
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
42
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
3
6
[2 3 4]
[4 5 6]
[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[20 40 60]
60
20.0
8.16496580927726
[ True  True  True]
[20 30]
[10 30]
[[1]
 [2]
 [3]
 [4]
 [5]]
[(25, 90.5) (30, 85.2)]
